# Generated by Django 5.2.3 on 2025-10-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Crítica'), ('WARNING', 'Advertencia'), ('INFO', 'Información')], default='INFO', max_length=10),
        ),
    ]
