# Generated by Django 5.2.3 on 2025-10-07 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alerta_severity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='Activar notificaciones')),
                ('enable_push_notifications', models.BooleanField(default=True, verbose_name='Notificaciones push')),
                ('enable_email_notifications', models.BooleanField(default=False, verbose_name='Notificaciones por email')),
                ('notify_critical_alerts', models.BooleanField(default=True, verbose_name='Alertas críticas')),
                ('notify_warning_alerts', models.BooleanField(default=True, verbose_name='Alertas de advertencia')),
                ('notify_info_alerts', models.BooleanField(default=False, verbose_name='Alertas informativas')),
                ('notify_barrier_events', models.BooleanField(default=True, verbose_name='Eventos de barrera')),
                ('notify_battery_low', models.BooleanField(default=True, verbose_name='Batería baja')),
                ('notify_communication_lost', models.BooleanField(default=True, verbose_name='Comunicación perdida')),
                ('notify_gabinete_open', models.BooleanField(default=True, verbose_name='Gabinete abierto')),
                ('notification_frequency', models.CharField(choices=[('IMMEDIATE', 'Inmediato'), ('HOURLY', 'Cada hora'), ('DAILY', 'Diario'), ('WEEKLY', 'Semanal')], default='IMMEDIATE', max_length=20, verbose_name='Frecuencia de notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
    ]
