# Generated by Django 5.2.3 on 2025-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['-created_at', 'cruce'], name='alerta_created_cruce_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['cruce', 'resolved'], name='alerta_cruce_resolved_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['severity', 'resolved'], name='alerta_severity_resolved_idx'),
        ),
        migrations.AddIndex(
            model_name='barrierevent',
            index=models.Index(fields=['-event_time', 'cruce'], name='barrier_event_time_cruce_idx'),
        ),
        migrations.AddIndex(
            model_name='barrierevent',
            index=models.Index(fields=['cruce', 'event_time'], name='barrier_cruce_event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='barrierevent',
            index=models.Index(fields=['state'], name='barrier_state_idx'),
        ),
        migrations.AddIndex(
            model_name='cruce',
            index=models.Index(fields=['estado'], name='cruce_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetria',
            index=models.Index(fields=['-timestamp', 'cruce'], name='telemetria_timestamp_cruce_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetria',
            index=models.Index(fields=['cruce', 'timestamp'], name='telemetria_cruce_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetria',
            index=models.Index(fields=['barrier_status'], name='telemetria_barrier_status_idx'),
        ),
    ]
