# Generated by Django 5.2.8 on 2025-11-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alerta_alerta_created_cruce_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cruce',
            options={'ordering': ['nombre'], 'verbose_name': 'Cruce', 'verbose_name_plural': 'Cruces'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['nombre'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Responsable'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_empresa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_horario',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes 8:00-18:00', max_length=200, verbose_name='Horario de Atención'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Responsable'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Responsable'),
        ),
    ]
