# Generated by Django 5.2.8 on 2025-11-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_responsable_fields_to_cruce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruce',
            name='responsable_email',
        ),
        migrations.RemoveField(
            model_name='cruce',
            name='responsable_empresa',
        ),
        migrations.RemoveField(
            model_name='cruce',
            name='responsable_horario',
        ),
        migrations.RemoveField(
            model_name='cruce',
            name='responsable_nombre',
        ),
        migrations.RemoveField(
            model_name='cruce',
            name='responsable_telefono',
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Regla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_mantenimiento', models.CharField(choices=[('BATERIA', 'Cambio de Batería'), ('SENSOR', 'Revisión de Sensor'), ('BARRERA', 'Mantenimiento de Barrera'), ('ENERGIA', 'Revisión de Sistema Energético'), ('GENERAL', 'Mantenimiento General'), ('LIMPIEZA', 'Limpieza y Revisión')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('condiciones', models.JSONField(default=dict, help_text='JSON con las condiciones que deben cumplirse', verbose_name='Condiciones de Activación')),
                ('acciones', models.JSONField(default=dict, help_text='JSON con las acciones a realizar cuando se active', verbose_name='Acciones')),
                ('generar_alerta', models.BooleanField(default=True, verbose_name='Generar Alerta Automática')),
                ('tipo_alerta', models.CharField(choices=[('LOW_BATTERY', 'Batería Baja'), ('SENSOR_ERROR', 'Error de Sensor'), ('BARRIER_STUCK', 'Barrera Bloqueada'), ('VOLTAGE_CRITICAL', 'Voltaje Crítico'), ('COMMUNICATION_LOST', 'Comunicación Perdida'), ('GABINETE_ABIERTO', 'Gabinete Abierto')], default='LOW_BATTERY', max_length=20, verbose_name='Tipo de Alerta')),
                ('severidad_alerta', models.CharField(choices=[('CRITICAL', 'Crítica'), ('WARNING', 'Advertencia'), ('INFO', 'Información')], default='WARNING', max_length=10, verbose_name='Severidad de Alerta')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('dias_semana', models.JSONField(blank=True, default=list, help_text='[0=Domingo, 1=Lunes, ..., 6=Sábado]', verbose_name='Días de la Semana')),
                ('activo', models.BooleanField(default=True, verbose_name='Regla Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cruce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_mantenimiento', to='api.cruce', verbose_name='Cruce Específico')),
            ],
            options={
                'verbose_name': 'Regla de Mantenimiento Preventivo',
                'verbose_name_plural': 'Reglas de Mantenimiento Preventivo',
                'ordering': ['-prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('BATERIA', 'Cambio de Batería'), ('SENSOR', 'Revisión de Sensor'), ('BARRERA', 'Mantenimiento de Barrera'), ('ENERGIA', 'Revisión de Sistema Energético'), ('GENERAL', 'Mantenimiento General'), ('LIMPIEZA', 'Limpieza y Revisión')], max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('descripcion', models.TextField(verbose_name='Descripción del Mantenimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable del Mantenimiento')),
                ('metricas_antes', models.JSONField(blank=True, default=dict, verbose_name='Métricas Antes')),
                ('metricas_despues', models.JSONField(blank=True, default=dict, verbose_name='Métricas Después')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cruce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='api.cruce')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones', to='api.mantenimientopreventivo')),
            ],
            options={
                'verbose_name': 'Historial de Mantenimiento',
                'verbose_name_plural': 'Historial de Mantenimientos',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='MetricasDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Métrica')),
                ('tiempo_activo', models.FloatField(default=0, help_text='Tiempo que el cruce estuvo operativo', verbose_name='Tiempo Activo (horas)')),
                ('tiempo_inactivo', models.FloatField(default=0, help_text='Tiempo que el cruce estuvo fuera de servicio', verbose_name='Tiempo Inactivo (horas)')),
                ('disponibilidad_porcentaje', models.FloatField(default=100, verbose_name='Disponibilidad (%)')),
                ('voltaje_promedio', models.FloatField(blank=True, null=True, verbose_name='Voltaje Promedio (V)')),
                ('voltaje_minimo', models.FloatField(blank=True, null=True, verbose_name='Voltaje Mínimo (V)')),
                ('voltaje_maximo', models.FloatField(blank=True, null=True, verbose_name='Voltaje Máximo (V)')),
                ('horas_bateria_baja', models.FloatField(default=0, help_text='Tiempo con voltaje < 11.5V', verbose_name='Horas con Batería Baja')),
                ('total_eventos_barrera', models.IntegerField(default=0, verbose_name='Total Eventos de Barrera')),
                ('total_alertas', models.IntegerField(default=0, verbose_name='Total Alertas')),
                ('alertas_criticas', models.IntegerField(default=0, verbose_name='Alertas Críticas')),
                ('alertas_resueltas', models.IntegerField(default=0, verbose_name='Alertas Resueltas')),
                ('total_telemetrias', models.IntegerField(default=0, verbose_name='Total Telemetrías Recibidas')),
                ('tiempo_sin_comunicacion', models.FloatField(default=0, verbose_name='Tiempo Sin Comunicación (horas)')),
                ('mantenimientos_realizados', models.IntegerField(default=0, verbose_name='Mantenimientos Realizados')),
                ('mantenimientos_preventivos', models.IntegerField(default=0, verbose_name='Mantenimientos Preventivos')),
                ('mantenimientos_correctivos', models.IntegerField(default=0, verbose_name='Mantenimientos Correctivos')),
                ('metricas_adicionales', models.JSONField(blank=True, default=dict, verbose_name='Métricas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cruce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='api.cruce')),
            ],
            options={
                'verbose_name': 'Métrica de Desempeño',
                'verbose_name_plural': 'Métricas de Desempeño',
                'ordering': ['-fecha', 'cruce'],
                'indexes': [models.Index(fields=['-fecha', 'cruce'], name='metricas_fecha_cruce_idx'), models.Index(fields=['cruce', 'disponibilidad_porcentaje'], name='metricas_cruce_disp_idx')],
                'unique_together': {('cruce', 'fecha')},
            },
        ),
    ]
