# Generated by Django 5.2.8 on 2025-11-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_mantenimiento_preventivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruce',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En mantenimiento'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
    ]
