# Generated by Django 5.2.8 on 2025-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cruce_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruce',
            name='responsable_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Responsable'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_horario',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes 8:00-18:00', max_length=200, null=True, verbose_name='Horario de Atención'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Responsable'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='responsable_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Responsable'),
        ),
    ]
